<a href="https://colab.research.google.com/github/cescotuner/data_akusisi_manajemen_kelompok/blob/main/Analisis_kebutuhan_storage_DAM_3_Kelompok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Analisis Kebutuhan Storage: Arsip Digital Sanggar Tari
Anggota Kelompok


1.   Francesco Nera Alfi Nanggor (2501010174)
2.   I Nyoman Chayanta Kusumadinata (2501010166)
3.   Putu Reva Dhamma Nanda (2501010167)

In [ ]:
import pandas as pd
from IPython.display import display, Markdown

# Judul
display(Markdown("# 1. Jenis Data Arsip Digital Sanggar Tari"))

# Daftar jenis data
data = {
    "No": [1, 2, 3, 4, 5, 6],
    "Jenis Data": [
        "Data Teks",
        "Data Gambar",
        "Data Audio",
        "Data Video",
        "Data Dokumen",
        "Data Spasial"
    ],
    "Contoh Data": [
        "Nama anggota, biodata penari, jadwal latihan, deskripsi tarian",
        "Foto anggota, foto latihan, kostum, dan pertunjukan",
        "Musik pengiring tari, rekaman gamelan, rekaman latihan",
        "Rekaman latihan, video pertunjukan, tutorial gerakan tari",
        "Proposal kegiatan, surat izin, laporan, sertifikat",
        "Lokasi sanggar, koordinat tempat latihan dan pertunjukan"
    ],
    "Format Data": [
        "TXT, CSV, JSON",
        "JPG, PNG, WEBP",
        "MP3, WAV, M4A",
        "MP4, MOV, MKV",
        "PDF, DOCX, XLSX",
        "CSV, GeoJSON, WKT"
    ]
}

df = pd.DataFrame(data)

# Menampilkan tabel
display(df)

# 1. Jenis Data Arsip Digital Sanggar Tari

,No,Jenis Data,Contoh Data,Format Data
0,1,Data Teks,"Nama anggota, biodata penari, jadwal latihan, ...","TXT, CSV, JSON"
1,2,Data Gambar,"Foto anggota, foto latihan, kostum, dan pertun...","JPG, PNG, WEBP"
2,3,Data Audio,"Musik pengiring tari, rekaman gamelan, rekaman...","MP3, WAV, M4A"
3,4,Data Video,"Rekaman latihan, video pertunjukan, tutorial g...","MP4, MOV, MKV"
4,5,Data Dokumen,"Proposal kegiatan, surat izin, laporan, sertif...","PDF, DOCX, XLSX"
5,6,Data Spasial,"Lokasi sanggar, koordinat tempat latihan dan p...","CSV, GeoJSON, WKT"

In [ ]:
display(Markdown("""
## 2. Karakteristik Setiap Jenis Data

Analisis karakteristik menggunakan enam pertanyaan ANAKSIMBA:
Apa, Di mana, Kapan, Siapa, Mengapa, dan Bagaimana.
"""))

karakteristik = pd.DataFrame({
    "Jenis Data": ["Teks", "Gambar", "Audio", "Spasial"],
    "1. Apa": [
        "Biodata anggota dan jadwal latihan",
        "Foto latihan dan pertunjukan",
        "Musik pengiring dan rekaman gamelan",
        "Koordinat sanggar dan lokasi pertunjukan"
    ],
    "2. Dimana": [
        "Data administrasi sanggar",
        "Lokasi latihan dan pementasan",
        "Kegiatan latihan dan pementasan",
        "Sanggar dan lokasi pertunjukan"
    ],
    "3. Kapan": [
        "Saat anggota atau jadwal diperbarui",
        "Saat latihan dan pertunjukan",
        "Saat latihan atau perekaman musik",
        "Saat lokasi baru dicatat"
    ],
    "4. Siapa": [
        "Pengurus dan anggota sanggar",
        "Fotografer, penari, dan pengurus",
        "Penabuh gamelan dan pengurus",
        "Pengurus dan petugas pendataan"
    ],
    "5. Mengapa": [
        "Untuk administrasi dan jadwal kegiatan",
        "Untuk dokumentasi dan pelestarian tari",
        "Untuk menyimpan musik pengiring tari",
        "Untuk mendata lokasi sanggar dan pertunjukan"
    ],
    "6. Bagaimana": [
        "Melalui formulir dan input digital",
        "Melalui kamera dan unggahan foto",
        "Melalui perekaman atau unggahan audio",
        "Melalui GPS atau pencatatan koordinat"
    ],
    "Format": [
        "TXT, CSV, JSON",
        "JPG, PNG, WEBP",
        "MP3, WAV, M4A",
        "CSV, GeoJSON, WKT"
    ],
    "Struktur": [
        "Karakter, kata, dan kalimat",
        "Piksel pembentuk gambar",
        "Sinyal suara digital",
        "Titik koordinat atau geometri"
    ],
    "Ukuran Rata-rata": [
        "5 KB per catatan",
        "3 MB per foto",
        "8 MB per file audio",
        "2 KB per catatan lokasi"
    ],
    "Pertumbuhan & Pengelolaan": [
        "Bertambah saat data anggota atau jadwal diperbarui",
        "Bertambah saat dokumentasi baru diunggah",
        "Bertambah saat rekaman baru dibuat",
        "Bertambah saat lokasi baru dicatat"
    ]
})

display(karakteristik)

## 2. Karakteristik Setiap Jenis Data

Analisis karakteristik menggunakan enam pertanyaan ANAKSIMBA:
Apa, Di mana, Kapan, Siapa, Mengapa, dan Bagaimana.

,Jenis Data,1. Apa,2. Di mana,3. Kapan,4. Siapa,5. Mengapa,6. Bagaimana,Format,Struktur,Ukuran Rata-rata,Pertumbuhan & Pengelolaan
0,Teks,Biodata anggota dan jadwal latihan,Data administrasi sanggar,Saat anggota atau jadwal diperbarui,Pengurus dan anggota sanggar,Untuk administrasi dan jadwal kegiatan,Melalui formulir dan input digital,"TXT, CSV, JSON","Karakter, kata, dan kalimat",5 KB per catatan,Bertambah saat data anggota atau jadwal diperb...
1,Gambar,Foto latihan dan pertunjukan,Lokasi latihan dan pementasan,Saat latihan dan pertunjukan,"Fotografer, penari, dan pengurus",Untuk dokumentasi dan pelestarian tari,Melalui kamera dan unggahan foto,"JPG, PNG, WEBP",Piksel pembentuk gambar,3 MB per foto,Bertambah saat dokumentasi baru diunggah
2,Audio,Musik pengiring dan rekaman gamelan,Kegiatan latihan dan pementasan,Saat latihan atau perekaman musik,Penabuh gamelan dan pengurus,Untuk menyimpan musik pengiring tari,Melalui perekaman atau unggahan audio,"MP3, WAV, M4A",Sinyal suara digital,8 MB per file audio,Bertambah saat rekaman baru dibuat
3,Spasial,Koordinat sanggar dan lokasi pertunjukan,Sanggar dan lokasi pertunjukan,Saat lokasi baru dicatat,Pengurus dan petugas pendataan,Untuk mendata lokasi sanggar dan pertunjukan,Melalui GPS atau pencatatan koordinat,"CSV, GeoJSON, WKT",Titik koordinat atau geometri,2 KB per catatan lokasi,Bertambah saat lokasi baru dicatat

In [ ]:
display(Markdown("""
## 3. Tabel Perbandingan Karakteristik Empat Jenis Data

(Format · Atribut teknis · Ukuran per unit · Volume & pertumbuhan · Variasi · Kebutuhan penyimpanan)
"""))

karakteristik = pd.DataFrame({
    "Atribut pembanding": [
        "1. Format",
        "2. Atribut teknis",
        "3. Ukuran per unit",
        "4. Volume & pertumbuhan",
        "5. Variasi",
        "6. Kebutuhan penyimpanan (metadata)"
    ],
    "Teks": [
        "TXT, CSV, JSON, DOCX",
        "Encoding UTF-8, jumlah karakter/kata, bahasa (Indonesia/Bali)",
        "Sangat kecil (2–15 KB per dokumen)",
        "Unit bisa banyak, tumbuh linear saat anggota/jadwal diperbarui",
        "Sedang–tinggi (noise, singkatan, multi-bahasa)",
        "Judul, tanggal, penulis, bahasa, kategori, encoding"
    ],
    "Gambar": [
        "JPG, PNG, WEBP, RAW",
        "Resolusi (lebar×tinggi), channel (RGB), bit depth 8",
        "Sedang–besar (0,8–4 MB per foto setelah kompresi)",
        "Unit tinggi, tumbuh cepat setiap latihan/pertunjukan",
        "Tinggi (kamera ponsel vs DSLR, indoor/outdoor, kompresi)",
        "Resolusi, format, kamera, tanggal, lokasi EXIF, tag tari/penari"
    ],
    "Audio": [
        "WAV (master), MP3, M4A/AAC",
        "Sample rate 44,1/48 kHz, bit depth 16/24, mono/stereo",
        "Sedang–besar (≈1–10 MB per menit, tergantung format)",
        "Tumbuh sebanding durasi rekaman gamelan/latihan",
        "Sedang (kualitas rekaman, noise latar belakang)",
        "Judul lagu, durasi, format, bit rate, tanggal perekaman"
    ]
})

display(karakteristik)

## 3. Tabel Perbandingan Karakteristik Empat Jenis Data

(Format · Atribut teknis · Ukuran per unit · Volume & pertumbuhan · Variasi · Kebutuhan penyimpanan)

,Atribut pembanding,Teks,Gambar,Audio
0,1. Format,"TXT, CSV, JSON, DOCX","JPG, PNG, WEBP, RAW","WAV (master), MP3, M4A/AAC"
1,2. Atribut teknis,"Encoding UTF-8, jumlah karakter/kata, bahasa (...","Resolusi (lebar×tinggi), channel (RGB), bit de...","Sample rate 44,1/48 kHz, bit depth 16/24, mono..."
2,3. Ukuran per unit,Sangat kecil (2–15 KB per dokumen),"Sedang–besar (0,8–4 MB per foto setelah kompresi)","Sedang–besar (≈1–10 MB per menit, tergantung f..."
3,4. Volume & pertumbuhan,"Unit bisa banyak, tumbuh linear saat anggota/j...","Unit tinggi, tumbuh cepat setiap latihan/pertu...",Tumbuh sebanding durasi rekaman gamelan/latihan
4,5. Variasi,"Sedang–tinggi (noise, singkatan, multi-bahasa)","Tinggi (kamera ponsel vs DSLR, indoor/outdoor,...","Sedang (kualitas rekaman, noise latar belakang)"
5,6. Kebutuhan penyimpanan (metadata),"Judul, tanggal, penulis, bahasa, kategori, enc...","Resolusi, format, kamera, tanggal, lokasi EXIF...","Judul lagu, durasi, format, bit rate, tanggal ..."

In [ ]:
import pandas as pd
display(Markdown("# 4. Asumsi jumlah unit dan ukuran rata-rata "))

#  Asumsi jumlah data dan ukuran rata-rata
data = {
    "No": [1, 2, 3, 4, 5, 6],

    "Jenis Data": [
        "Data Teks",
        "Data Gambar",
        "Data Audio",
        "Data Video",
        "Data Dokumen",
        "Data Spasial"
    ],

    "Jumlah Unit": [
        500,
        1000,
        200,
        100,
        300,
        50
    ],

    "Ukuran Rata-rata": [
        "5 KB",
        "3 MB",
        "5 MB",
        "150 MB",
        "2 MB",
        "10 KB"
    ]
}

# Membuat tabel
df = pd.DataFrame(data)

# Menampilkan tabel
display(df)

# 4. Asumsi jumlah unit dan ukuran rata-rata

   No    Jenis Data  Jumlah Unit Ukuran Rata-rata
0   1     Data Teks          500             5 KB
1   2   Data Gambar         1000             3 MB
2   3    Data Audio          200             5 MB
3   4    Data Video          100           150 MB
4   5  Data Dokumen          300             2 MB
5   6  Data Spasial           50            10 KB

In [20]:
import pandas as pd
display(Markdown("# 5. Skenario akuisisi data "))

# ==========================================
# SKENARIO AKUISISI DATA
# ==========================================

skenario = {
    "Jenis Data": [
        "Teks",
        "Gambar",
        "Audio",
        "Video",
        "Dokumen",
        "Spasial"
    ],

    "Sumber Data": [
        "Pengurus sanggar",
        "Kegiatan sanggar",
        "Latihan tari",
        "Pertunjukan tari",
        "Administrasi sanggar",
        "Lokasi kegiatan"
    ],

    "Metode Akuisisi": [
        "Pendataan anggota dan jadwal latihan",
        "Pengambilan foto menggunakan kamera",
        "Perekaman musik gamelan",
        "Perekaman pertunjukan menggunakan kamera",
        "Pengumpulan dokumen digital",
        "Pengambilan koordinat GPS"
    ],

    "Frekuensi": [
        "Setiap bulan",
        "Setiap kegiatan",
        "Setiap latihan terpilih",
        "Setiap pertunjukan",
        "Setiap ada dokumen baru",
        "Setiap ada lokasi baru"
    ]
}

df_skenario = pd.DataFrame(skenario)
display(df_skenario)


# ==========================================
# ASUMSI JUMLAH DATA DAN UKURAN RATA-RATA
# ==========================================

print("\nASUMSI JUMLAH DATA DAN UKURAN RATA-RATA")

jenis_data = [
    "Teks", "Gambar", "Audio",
    "Video", "Dokumen", "Spasial"
]

jumlah_unit = [500, 1000, 200, 100, 300, 50]

ukuran_rata = [
    "5 KB", "3 MB", "5 MB",
    "150 MB", "2 MB", "10 KB"
]

# Konversi semua ukuran menjadi MB
ukuran_mb = [5/1024, 3, 5, 150, 2, 10/1024]

df_asumsi = pd.DataFrame({
    "Jenis Data": jenis_data,
    "Jumlah Unit": jumlah_unit,
    "Ukuran Rata-rata": ukuran_rata
})

display(df_asumsi)


# ==========================================
# MENGHITUNG STORAGE BULAN PERTAMA
# ==========================================

storage_awal = sum(
    jumlah * ukuran
    for jumlah, ukuran in zip(jumlah_unit, ukuran_mb)
)

print(f"\nStorage Bulan Pertama: {storage_awal:.2f} MB")


# ==========================================
# ESTIMASI PERTUMBUHAN 10% SELAMA 12 BULAN
# ==========================================

print("\nESTIMASI STORAGE SELAMA 12 BULAN")

pertumbuhan = 0.10
akumulasi = 0
hasil = []

for bulan in range(1, 13):

    storage_bulanan = storage_awal * (1 + pertumbuhan) ** (bulan - 1)

    akumulasi += storage_bulanan

    hasil.append({
        "Bulan": bulan,
        "Data Baru (MB)": round(storage_bulanan, 2),
        "Akumulasi Storage (MB)": round(akumulasi, 2)
    })

df_hasil = pd.DataFrame(hasil)

display(df_hasil)


# ==========================================
# HASIL AKHIR
# ==========================================

print("\nHASIL ESTIMASI PENYIMPANAN")

print(f"Storage Bulan Pertama : {storage_awal:.2f} MB")
print(f"Pertumbuhan Per Bulan : {pertumbuhan * 100:.0f}%")
print(f"Total Storage 1 Tahun : {akumulasi:.2f} MB")
print(f"Total Storage 1 Tahun : {akumulasi / 1024:.2f} GB")

# 5. Skenario akuisisi data

,Jenis Data,Sumber Data,Metode Akuisisi,Frekuensi
0,Teks,Pengurus sanggar,Pendataan anggota dan jadwal latihan,Setiap bulan
1,Gambar,Kegiatan sanggar,Pengambilan foto menggunakan kamera,Setiap kegiatan
2,Audio,Latihan tari,Perekaman musik gamelan,Setiap latihan terpilih
3,Video,Pertunjukan tari,Perekaman pertunjukan menggunakan kamera,Setiap pertunjukan
4,Dokumen,Administrasi sanggar,Pengumpulan dokumen digital,Setiap ada dokumen baru
5,Spasial,Lokasi kegiatan,Pengambilan koordinat GPS,Setiap ada lokasi baru

ASUMSI JUMLAH DATA DAN UKURAN RATA-RATA

  Jenis Data  Jumlah Unit Ukuran Rata-rata
0       Teks          500             5 KB
1     Gambar         1000             3 MB
2      Audio          200             5 MB
3      Video          100           150 MB
4    Dokumen          300             2 MB
5    Spasial           50            10 KB

Storage Bulan Pertama: 19602.93 MB

ESTIMASI STORAGE SELAMA 12 BULAN

    Bulan  Data Baru (MB)  Akumulasi Storage (MB)
0       1        19602.93                19602.93
1       2        21563.22                41166.15
2       3        23719.54                64885.70
3       4        26091.50                90977.20
4       5        28700.65               119677.85
5       6        31570.71               151248.56
6       7        34727.79               185976.35
7       8        38200.56               224176.91
8       9        42020.62               266197.53
9      10        46222.68               312420.21
10     11        50844.95               363265.16
11     12        55929.45               419194.61

HASIL ESTIMASI PENYIMPANAN
Storage Bulan Pertama : 19602.93 MB
Pertumbuhan Per Bulan : 10%
Total Storage 1 Tahun : 419194.61 MB
Total Storage 1 Tahun : 409.37 GB

In [21]:
import pandas as pd
display(Markdown("# 6. Estimasi total storage + cadangan 30% "))
# Data asumsi penyimpanan
data_storage = {
    "Jenis Data": [
        "Data Teks",
        "Data Gambar",
        "Data Audio",
        "Data Video",
        "Data Dokumen",
        "Data Spasial"
    ],
    "Jumlah Unit": [500, 1000, 200, 100, 300, 50],
    "Ukuran Rata-rata (MB)": [
        5 / 1024,
        3,
        5,
        150,
        2,
        10 / 1024
    ]
}

# Membuat DataFrame
df_storage = pd.DataFrame(data_storage)

# Menghitung total setiap jenis data
df_storage["Total Storage (MB)"] = (
    df_storage["Jumlah Unit"] *
    df_storage["Ukuran Rata-rata (MB)"]
)

# Menampilkan tabel
display(df_storage.round(2))

# Menghitung total keseluruhan
total_storage = df_storage["Total Storage (MB)"].sum()

# Menghitung cadangan 30%
cadangan = total_storage * 0.30

# Menghitung total akhir
total_akhir = total_storage + cadangan

print("\nHASIL ESTIMASI PENYIMPANAN")
print(f"Total Storage : {total_storage:.2f} MB")
print(f"Cadangan 30%  : {cadangan:.2f} MB")
print(f"Total Akhir   : {total_akhir:.2f} MB")
print(f"Total dalam GB: {total_akhir / 1024:.2f} GB")

# 6. Estimasi total storage + cadangan 30%

     Jenis Data  Jumlah Unit  Ukuran Rata-rata (MB)  Total Storage (MB)
0     Data Teks          500                   0.00                2.44
1   Data Gambar         1000                   3.00             3000.00
2    Data Audio          200                   5.00             1000.00
3    Data Video          100                 150.00            15000.00
4  Data Dokumen          300                   2.00              600.00
5  Data Spasial           50                   0.01                0.49

HASIL ESTIMASI PENYIMPANAN
Total Storage : 19602.93 MB
Cadangan 30%  : 5880.88 MB
Total Akhir   : 25483.81 MB
Total dalam GB: 24.89 GB

# 7. Mengapa Multimedia Sebaiknya Tidak Langsung Disimpan sebagai BLOB?

BLOB (Binary Large Object) adalah tipe data yang dapat
menyimpan data biner, seperti gambar, audio, dan video,
secara langsung di dalam database.

Penyimpanan BLOB memiliki kelebihan, seperti pengelolaan file
dan metadata dalam satu sistem serta dukungan transaksi
database. Namun, file multimedia berukuran besar dapat
meningkatkan ukuran database, kebutuhan backup, dan beban
pemulihan data. Dampaknya bergantung pada DBMS dan arsitektur
yang digunakan.

Untuk arsip digital sanggar tari, file gambar, audio, dan video
dapat disimpan di file system atau object storage. Database
relasional menyimpan metadata seperti nama file, format,
ukuran, tanggal unggah, dan lokasi penyimpanan file.

Pendekatan ini memisahkan data terstruktur dari file multimedia
sehingga pengelolaan file besar dapat dilakukan secara terpisah.
Namun, backup, keamanan akses, dan hubungan antara metadata
serta file tetap harus dikelola dengan baik.

BLOB tetap dapat menjadi pilihan yang sesuai untuk file kecil
atau kebutuhan aplikasi tertentu. Jadi, pemilihan metode
penyimpanan perlu mempertimbangkan ukuran file, kebutuhan
akses, backup, keamanan, dan karakteristik aplikasi.